# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04' # examples of other options: 'macOS-10.13', 'vs2017-win2016'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.300'
- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: 'C:\Users\Snehanshu\source\repos\MvcMovie\MvcMovie.csproj'
    feedsToUse: config
    nugetConfigPath: NuGet.config    # Relative to root of the repository
    externalFeedCredentials: <Name of the NuGet service connection>


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
